name: "📖 General"

description: Create a new ticket for something important that need to be addressed in future
title: ""

labels: [
  "enhancement"
]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Type what you need to remember...
    validations:
      required: true